/* #Voleqy
$[
	1.063,
	["BLINDZEUS_SETAISETTINGSDIALOG",[[0,0,1,1],0.025,0.04,"GUI_GRID"],0,1,0],
	[2200,"",[2,"",["7 * GUI_GRID_W + GUI_GRID_X","4.5 * GUI_GRID_H + GUI_GRID_Y","22.5 * GUI_GRID_W","11.5 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[1800,"",[2,"Set AI Settings",["7.5 * GUI_GRID_W + GUI_GRID_X","4.5 * GUI_GRID_H + GUI_GRID_Y","21.5 * GUI_GRID_W","11 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","1"],[]],
	[1801,"",[2,"Vehicle Specific settings",["15.5 * GUI_GRID_W + GUI_GRID_X","5 * GUI_GRID_H + GUI_GRID_Y","13 * GUI_GRID_W","4 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","1"],[]],
	[1600,"",[2,"OK",["25 * GUI_GRID_W + GUI_GRID_X","11 * GUI_GRID_H + GUI_GRID_Y","3.5 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[1601,"",[2,"Cancel",["25 * GUI_GRID_W + GUI_GRID_X","13 * GUI_GRID_H + GUI_GRID_Y","3.5 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[1802,"",[2,"Selection",["7.5 * GUI_GRID_W + GUI_GRID_X","10 * GUI_GRID_H + GUI_GRID_Y","21.5 * GUI_GRID_W","5.5 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","1"],[]],
	[1000,"",[2,"Apply to all Editable objects: ",["7.5 * GUI_GRID_W + GUI_GRID_X","11 * GUI_GRID_H + GUI_GRID_Y","7.5 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1001,"",[2,"Apply to vehicle or group  under module :",["7.5 * GUI_GRID_W + GUI_GRID_X","12 * GUI_GRID_H + GUI_GRID_Y","11 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1002,"",[2,"Apply each time you give vehicle or group a waypoint :",["7.5 * GUI_GRID_W + GUI_GRID_X","13 * GUI_GRID_H + GUI_GRID_Y","13.5 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1003,"",[2,"AutoCombat :",["8 * GUI_GRID_W + GUI_GRID_X","6 * GUI_GRID_H + GUI_GRID_Y","8 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1004,"",[2,"Allow Fleeing :",["8 * GUI_GRID_W + GUI_GRID_X","7 * GUI_GRID_H + GUI_GRID_Y","8 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1005,"",[2,"Enable Attack :",["8 * GUI_GRID_W + GUI_GRID_X","8 * GUI_GRID_H + GUI_GRID_Y","8 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1006,"",[2,"Unload in combat,",["16 * GUI_GRID_W + GUI_GRID_X","6.5 * GUI_GRID_H + GUI_GRID_Y","8 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1007,"",[2,"Crew remains in Immobilized :",["16 * GUI_GRID_W + GUI_GRID_X","8 * GUI_GRID_H + GUI_GRID_Y","8 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1008,"",[2,"Turrets:",["21 * GUI_GRID_W + GUI_GRID_X","6.5 * GUI_GRID_H + GUI_GRID_Y","2.5 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1009,"",[2,"Cargo:",["24.5 * GUI_GRID_W + GUI_GRID_X","6.5 * GUI_GRID_H + GUI_GRID_Y","2.5 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[2800,"",[2,"",["21.5 * GUI_GRID_W + GUI_GRID_X","11 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2801,"",[2,"",["21.5 * GUI_GRID_W + GUI_GRID_X","12 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2802,"",[2,"",["21.5 * GUI_GRID_W + GUI_GRID_X","13 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2803,"",[2,"",["13 * GUI_GRID_W + GUI_GRID_X","6 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2804,"",[2,"",["13 * GUI_GRID_W + GUI_GRID_X","7 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2805,"",[2,"",["13 * GUI_GRID_W + GUI_GRID_X","8 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2806,"",[2,"",["23.5 * GUI_GRID_W + GUI_GRID_X","6.5 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2807,"",[2,"",["24 * GUI_GRID_W + GUI_GRID_X","8 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[2808,"",[2,"",["26.5 * GUI_GRID_W + GUI_GRID_X","6.5 * GUI_GRID_H + GUI_GRID_Y","1 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","-1"],[]],
	[1010,"",[2,"Waypoint checking:",["7.5 * GUI_GRID_W + GUI_GRID_X","14 * GUI_GRID_H + GUI_GRID_Y","5 * GUI_GRID_W","1 * GUI_GRID_H"],[-1,-1,-1,-1],[-1,-1,-1,-1],[-1,-1,-1,-1],"","0.7"],[]],
	[1011,"",[2,"Disabled",["12.5 * GUI_GRID_W + GUI_GRID_X","14 * GUI_GRID_H + GUI_GRID_Y","3 * GUI_GRID_W","1 * GUI_GRID_H"],[0,1,0,1],[-1,-1,-1,-1],[-1,-1,-1,-1],"Tells if the settings are being applied to each group and vehicle you are issuing waypoints","0.7"],[]]
]
*/

controls[]=
{
	IGUIBack_2200,
	RscFrame_1800,
	RscFrame_1801,
	RscButton_1600,
	RscButton_1601,
	RscFrame_1802,
	RscText_1000,
	RscText_1001,
	RscText_1002,
	RscText_1003,
	RscText_1004,
	RscText_1005,
	RscText_1006,
	RscText_1007,
	RscText_1008,
	RscText_1009,
	RscCheckbox_2800,
	RscCheckbox_2801,
	RscCheckbox_2802,
	RscCheckbox_2803,
	RscCheckbox_2804,
	RscCheckbox_2805,
	RscCheckbox_2806,
	RscCheckbox_2807,
	RscCheckbox_2808,
	RscText_1010,
	RscText_1011
};
////////////////////////////////////////////////////////
// GUI EDITOR OUTPUT START (by Bummeri, v1.063, #Voleqy)
////////////////////////////////////////////////////////

class IGUIBack_2200: IGUIBack
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_IGUIBACK_2200;
	x = 7 * GUI_GRID_W + GUI_GRID_X;
	y = 4.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 22.5 * GUI_GRID_W;
	h = 11.5 * GUI_GRID_H;
};
class RscFrame_1800: RscFrame
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCFRAME_1800;
	text = "Set AI Settings"; //--- ToDo: Localize;
	x = 7.5 * GUI_GRID_W + GUI_GRID_X;
	y = 4.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 21.5 * GUI_GRID_W;
	h = 11 * GUI_GRID_H;
	sizeEx = 1 * GUI_GRID_H;
};
class RscFrame_1801: RscFrame
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCFRAME_1801;
	text = "Vehicle Specific settings"; //--- ToDo: Localize;
	x = 15.5 * GUI_GRID_W + GUI_GRID_X;
	y = 5 * GUI_GRID_H + GUI_GRID_Y;
	w = 13 * GUI_GRID_W;
	h = 4 * GUI_GRID_H;
	sizeEx = 1 * GUI_GRID_H;
};
class RscButton_1600: RscButton
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCBUTTON_1600;
	text = "OK"; //--- ToDo: Localize;
	x = 25 * GUI_GRID_W + GUI_GRID_X;
	y = 11 * GUI_GRID_H + GUI_GRID_Y;
	w = 3.5 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscButton_1601: RscButton
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCBUTTON_1601;
	text = "Cancel"; //--- ToDo: Localize;
	x = 25 * GUI_GRID_W + GUI_GRID_X;
	y = 13 * GUI_GRID_H + GUI_GRID_Y;
	w = 3.5 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscFrame_1802: RscFrame
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCFRAME_1802;
	text = "Selection"; //--- ToDo: Localize;
	x = 7.5 * GUI_GRID_W + GUI_GRID_X;
	y = 10 * GUI_GRID_H + GUI_GRID_Y;
	w = 21.5 * GUI_GRID_W;
	h = 5.5 * GUI_GRID_H;
	sizeEx = 1 * GUI_GRID_H;
};
class RscText_1000: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1000;
	text = "Apply to all Editable objects: "; //--- ToDo: Localize;
	x = 7.5 * GUI_GRID_W + GUI_GRID_X;
	y = 11 * GUI_GRID_H + GUI_GRID_Y;
	w = 7.5 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1001: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1001;
	text = "Apply to vehicle or group  under module :"; //--- ToDo: Localize;
	x = 7.5 * GUI_GRID_W + GUI_GRID_X;
	y = 12 * GUI_GRID_H + GUI_GRID_Y;
	w = 11 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1002: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1002;
	text = "Apply each time you give vehicle or group a waypoint :"; //--- ToDo: Localize;
	x = 7.5 * GUI_GRID_W + GUI_GRID_X;
	y = 13 * GUI_GRID_H + GUI_GRID_Y;
	w = 13.5 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1003: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1003;
	text = "AutoCombat :"; //--- ToDo: Localize;
	x = 8 * GUI_GRID_W + GUI_GRID_X;
	y = 6 * GUI_GRID_H + GUI_GRID_Y;
	w = 8 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1004: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1004;
	text = "Allow Fleeing :"; //--- ToDo: Localize;
	x = 8 * GUI_GRID_W + GUI_GRID_X;
	y = 7 * GUI_GRID_H + GUI_GRID_Y;
	w = 8 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1005: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1005;
	text = "Enable Attack :"; //--- ToDo: Localize;
	x = 8 * GUI_GRID_W + GUI_GRID_X;
	y = 8 * GUI_GRID_H + GUI_GRID_Y;
	w = 8 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1006: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1006;
	text = "Unload in combat,"; //--- ToDo: Localize;
	x = 16 * GUI_GRID_W + GUI_GRID_X;
	y = 6.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 8 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1007: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1007;
	text = "Crew remains in Immobilized :"; //--- ToDo: Localize;
	x = 16 * GUI_GRID_W + GUI_GRID_X;
	y = 8 * GUI_GRID_H + GUI_GRID_Y;
	w = 8 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1008: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1008;
	text = "Turrets:"; //--- ToDo: Localize;
	x = 21 * GUI_GRID_W + GUI_GRID_X;
	y = 6.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 2.5 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1009: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1009;
	text = "Cargo:"; //--- ToDo: Localize;
	x = 24.5 * GUI_GRID_W + GUI_GRID_X;
	y = 6.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 2.5 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscCheckbox_2800: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2800;
	x = 21.5 * GUI_GRID_W + GUI_GRID_X;
	y = 11 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2801: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2801;
	x = 21.5 * GUI_GRID_W + GUI_GRID_X;
	y = 12 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2802: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2802;
	x = 21.5 * GUI_GRID_W + GUI_GRID_X;
	y = 13 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2803: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2803;
	x = 13 * GUI_GRID_W + GUI_GRID_X;
	y = 6 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2804: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2804;
	x = 13 * GUI_GRID_W + GUI_GRID_X;
	y = 7 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2805: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2805;
	x = 13 * GUI_GRID_W + GUI_GRID_X;
	y = 8 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2806: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2806;
	x = 23.5 * GUI_GRID_W + GUI_GRID_X;
	y = 6.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2807: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2807;
	x = 24 * GUI_GRID_W + GUI_GRID_X;
	y = 8 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscCheckbox_2808: RscCheckbox
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCCHECKBOX_2808;
	x = 26.5 * GUI_GRID_W + GUI_GRID_X;
	y = 6.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 1 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
};
class RscText_1010: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1010;
	text = "Waypoint checking:"; //--- ToDo: Localize;
	x = 7.5 * GUI_GRID_W + GUI_GRID_X;
	y = 14 * GUI_GRID_H + GUI_GRID_Y;
	w = 5 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	sizeEx = 0.7 * GUI_GRID_H;
};
class RscText_1011: RscText
{
	idc = IDC_BLINDZEUS_SETAISETTINGSDIALOG_RSCTEXT_1011;
	text = "Disabled"; //--- ToDo: Localize;
	x = 12.5 * GUI_GRID_W + GUI_GRID_X;
	y = 14 * GUI_GRID_H + GUI_GRID_Y;
	w = 3 * GUI_GRID_W;
	h = 1 * GUI_GRID_H;
	colorText[] = {0,1,0,1};
	tooltip = "Tells if the settings are being applied to each group and vehicle you are issuing waypoints"; //--- ToDo: Localize;
	sizeEx = 0.7 * GUI_GRID_H;
};
////////////////////////////////////////////////////////
// GUI EDITOR OUTPUT END
////////////////////////////////////////////////////////
